<?php
/**
 * @copyright 2017 City of Bloomington, Indiana
 * @license https://www.gnu.org/licenses/old-licenses/gpl-2.0 GNU/GPL2, see LICENSE
 *
 * This file is part of the Google Calendar drupal module.
 *
 * The calendar module is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * The calendar module is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the calendar module.  If not, see <https://www.gnu.org/licenses/old-licenses/gpl-2.0/>.
 */
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\onboard\OnBoardService;

/**
 * @implements hook_help()
 */
function calendar_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        case 'help.page.onboard':
            return "<h2>Google Calendar Help</h2>";
        break;
    }
}

/**
 * @implements hook_theme()
 * @see https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Render!theme.api.php/function/hook_theme/8.2.x
 */
function calendar_theme()
{
    return [
        'calendar_events'=> [
            'template'  => 'calendar_events',
            'variables' => [
                'events'     => [],
                'calendarId' => ''
            ]
        ]
    ];
}
